### PR TITLE
Set ON_ERROR_STOP when running SQL migration

### PR DESCRIPTION
**Pull request by oschwald**
Unfortunately, there aren't any existing tests of the actual migration functionality and I did not add any specific to this behavior. I did manually test the change.

### CODE REVIEW

**Comment by oschwald** [comment]
AFAICT, the 5.8 failure is unrelated to my changes. It seems to be some sort of `File::Slurp` issue. I see there is an unreleased commit on `Database::Migrator` that switches it to `File::Slurp::Tiny`. I wonder if we should update that to `File::Slurper` and do a release.

**Comment by autarch** [comment]
I gave you comaint on PAUSE and access on GitHub. Let me know if anyone else from MaxMind would like this as well.

**Comment by autarch** [comment]
Re: `File::Slurper` - that sounds like a good idea.

**Comment by oschwald** [comment]
Thanks!

**Pull request merged**
